//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AzioniStrutture
    {
        public int Id { get; set; }
        public Nullable<int> IdAzione { get; set; }
        public Nullable<int> IdStruttura { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<int> Anno { get; set; }
        public string Grandezza { get; set; }
        public Nullable<double> Valore { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
    
        public virtual Azioni Azioni { get; set; }
        public virtual Grandezze Grandezze { get; set; }
        public virtual Strutture Strutture { get; set; }
    }
}
