//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CGIL_SOSTENIBILEContext : DbContext
    {
        public CGIL_SOSTENIBILEContext()
            : base("name=CGIL_SOSTENIBILEContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Azioni> Azionis { get; set; }
        public virtual DbSet<AzioniStrutture> AzioniStruttures { get; set; }
        public virtual DbSet<ConversioneGrandezze> ConversioneGrandezzes { get; set; }
        public virtual DbSet<Grandezze> Grandezzes { get; set; }
        public virtual DbSet<Strutture> Struttures { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Classifica> Classificas { get; set; }
    }
}
