//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classifica
    {
        public long NumeroClassifica { get; set; }
        public string Struttura { get; set; }
        public Nullable<double> Valore { get; set; }
        public string Grandezza { get; set; }
        public Nullable<double> ValoreEquivalente { get; set; }
        public string GrandezzaDestinazione { get; set; }
    }
}
